name:                wasmfromthegroundup
version:             0.1.0.0
github:              "J3RN/wasmfromthegroundup"
license:             BSD-3-Clause
author:              "Jonathan Arnett"
maintainer:          "jonathan.arnett@proton.me"
copyright:           "2025 Jonathan Arnett"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/J3RN/wasmfromthegroundup#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- bytestring
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - BinaryLiterals

executables:
  wasmfromthegroundup-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wasmfromthegroundup
    default-extensions:
      - OverloadedStrings

tests:
  wasmfromthegroundup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wasmfromthegroundup
      - hspec
    default-extensions:
      - OverloadedStrings
      - BinaryLiterals
